// packages/vue/src/ExcelPreview.vue
<script setup lang="ts">
/**
 * ExcelPreview - Excel 文件预览组件
 *
 * 渲染 Excel 解析后的 HTML 表格，支持多 Sheet 切换。
 *
 * @example
 * ```vue
 * <ExcelPreview
 *   :loading="preview.loading.value"
 *   :error="preview.error.value"
 *   :html="preview.html.value"
 *   :sheets="preview.sheets.value"
 *   :active-sheet="preview.activeSheet.value"
 *   @sheet-change="preview.switchSheet"
 * />
 * ```
 */

import { computed } from 'vue';
import type { SheetInfo } from '@bsg-export/types';

/** 组件 Props */
export interface ExcelPreviewProps {
  /** 是否正在解析 */
  loading?: boolean;
  /** 错误信息 */
  error?: string | null;
  /** HTML 输出 */
  html?: string | null;
  /** 工作表列表 */
  sheets?: SheetInfo[];
  /** 当前活动 Sheet 索引 */
  activeSheet?: number;
  /** 表格容器最大高度 */
  maxHeight?: string | number;
}

const props = withDefaults(defineProps<ExcelPreviewProps>(), {
  loading: false,
  error: null,
  html: null,
  sheets: () => [],
  activeSheet: 0,
  maxHeight: '600px',
});

const emit = defineEmits<{
  /** Sheet 切换 */
  sheetChange: [index: number];
}>();

/** 是否显示 Sheet 标签栏 */
const showSheetTabs = computed(() => props.sheets.length > 1);

/** 最大高度样式值 */
const maxHeightStyle = computed(() =>
  typeof props.maxHeight === 'number' ? `${props.maxHeight}px` : props.maxHeight
);
</script>

<template>
  <div>
    <!-- 加载中 -->
    <div v-if="loading">加载中...</div>

    <!-- 错误信息 -->
    <div v-else-if="error" style="color: red">{{ error }}</div>

    <!-- 预览内容 -->
    <template v-else-if="html">
      <!-- 表格预览区域 -->
      <div
        :style="{
          overflow: 'auto',
          maxHeight: maxHeightStyle,
          border: '1px solid #e0e0e0',
          borderRadius: '4px',
        }"
        v-html="html"
      />

      <!-- Sheet 标签栏 -->
      <div
        v-if="showSheetTabs"
        :style="{
          display: 'flex',
          gap: '2px',
          marginTop: '8px',
          borderTop: '1px solid #e0e0e0',
          paddingTop: '8px',
        }"
      >
        <button
          v-for="(sheet, index) in sheets"
          :key="sheet.name"
          :style="{
            padding: '4px 12px',
            border: '1px solid #ccc',
            borderRadius: '4px 4px 0 0',
            background: index === activeSheet ? '#fff' : '#f5f5f5',
            fontWeight: index === activeSheet ? 'bold' : 'normal',
            cursor: 'pointer',
            fontSize: '12px',
          }"
          @click="emit('sheetChange', index)"
        >
          {{ sheet.name }}
        </button>
      </div>
    </template>
  </div>
</template>

// packages/react/src/ExcelPreview.tsx
/**
 * ExcelPreview - Excel 文件预览组件
 *
 * 渲染 Excel 解析后的 HTML 表格，支持多 Sheet 切换。
 *
 * @example
 * ```tsx
 * const preview = useExcelPreview({ ... });
 *
 * <ExcelPreview
 *   state={preview}
 *   onSheetChange={preview.switchSheet}
 *   maxHeight="500px"
 * />
 * ```
 */

import React from 'react';
import type { ExcelPreviewState } from './useExcelPreview';

/** ExcelPreview 组件属性 */
export interface ExcelPreviewProps {
  /** 预览状态（来自 useExcelPreview） */
  state: ExcelPreviewState;
  /** 切换 Sheet 回调 */
  onSheetChange?: (index: number) => void;
  /** 容器类名 */
  className?: string;
  /** 容器样式 */
  style?: React.CSSProperties;
  /** 表格容器最大高度 */
  maxHeight?: string | number;
}

/** Excel 预览组件 */
export const ExcelPreview: React.FC<ExcelPreviewProps> = ({
  state,
  onSheetChange,
  className,
  style,
  maxHeight = '600px',
}) => {
  if (state.loading) {
    return <div className={className} style={style}>加载中...</div>;
  }

  if (state.error) {
    return <div className={className} style={{ color: 'red', ...style }}>{state.error}</div>;
  }

  if (!state.html) {
    return null;
  }

  return (
    <div className={className} style={style}>
      {/* 表格预览区域 */}
      <div
        style={{
          overflow: 'auto',
          maxHeight,
          border: '1px solid #e0e0e0',
          borderRadius: '4px',
        }}
        dangerouslySetInnerHTML={{ __html: state.html }}
      />

      {/* Sheet 标签栏 */}
      {state.sheets.length > 1 && (
        <div style={{
          display: 'flex',
          gap: '2px',
          marginTop: '8px',
          borderTop: '1px solid #e0e0e0',
          paddingTop: '8px',
        }}>
          {state.sheets.map((sheet, index) => (
            <button
              key={sheet.name}
              onClick={() => onSheetChange?.(index)}
              style={{
                padding: '4px 12px',
                border: '1px solid #ccc',
                borderRadius: '4px 4px 0 0',
                background: index === state.activeSheet ? '#fff' : '#f5f5f5',
                fontWeight: index === state.activeSheet ? 'bold' : 'normal',
                cursor: 'pointer',
                fontSize: '12px',
              }}
            >
              {sheet.name}
            </button>
          ))}
        </div>
      )}
    </div>
  );
};
